<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.kingtype</groupId>
        <artifactId>kingtype-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>kingtype-job</artifactId>

    <description>
        kingtype-job 任务调度模块
    </description>

    <dependencies>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-nacos</artifactId>
        </dependency>

        <!-- RuoYi Common Log -->
        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-log</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-dubbo</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-job</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-tenant</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.kingtype</groupId>
                    <artifactId>kingtype-common-mybatis</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-security</artifactId>
        </dependency>

        <!-- RuoYi Api System -->
        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-api-system</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
