<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.kingtype</groupId>
        <artifactId>OLT-Cloud-Plus</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>kingtype-monitor</module>
        <module>kingtype-seata-server</module>
        <module>kingtype-nacos</module>
        <module>kingtype-snailjob-server</module>
    </modules>

    <artifactId>kingtype-visual</artifactId>
    <packaging>pom</packaging>

    <description>
        kingtype-visual图形化管理模块
    </description>

    <dependencies>
        <!-- ELK 日志收集 -->
<!--        <dependency>-->
<!--            <groupId>com.kingtype</groupId>-->
<!--            <artifactId>kingtype-common-logstash</artifactId>-->
<!--        </dependency>-->

        <!-- skywalking 日志收集 -->
<!--        <dependency>-->
<!--            <groupId>com.kingtype</groupId>-->
<!--            <artifactId>kingtype-common-skylog</artifactId>-->
<!--        </dependency>-->

        <!-- prometheus 监控 -->
<!--        <dependency>-->
<!--            <groupId>com.kingtype</groupId>-->
<!--            <artifactId>kingtype-common-prometheus</artifactId>-->
<!--        </dependency>-->
    </dependencies>

</project>
