<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.kingtype</groupId>
        <artifactId>kingtype-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>kingtype-resource</artifactId>

    <description>
        kingtype-resource资源服务
    </description>

    <dependencies>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-nacos</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-dubbo</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-seata</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-log</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-idempotent</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-oss</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-ratelimiter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-mail</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-translation</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-websocket</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-sse</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-common-service-impl</artifactId>
        </dependency>

        <!-- RuoYi Api System -->
        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-api-system</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kingtype</groupId>
            <artifactId>kingtype-api-resource</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
